FROM {{.Base}}

LABEL org.opencontainers.image.source="{{.SourceURL}}" \
      org.opencontainers.image.title="{{.Title}}"{{if .Description}} \
      org.opencontainers.image.description="{{.Description}}"{{end}}

ARG TARGETARCH
ENV ARCH=$TARGETARCH

{{template "zypper.tmpl" .Packages}}

{{range .Tools}}# {{.Name}} {{.Version}}
{{.Install.Render}}

{{end}}{{if .HasGoInstall}}# Cleanup Go caches
RUN go clean -cache -modcache

{{end}}# Set up runner user with UID 1001 to match GitHub Actions expectations
RUN groupadd -g 121 runner && useradd -u 1001 -g 121 -m runner

{{if .HasAnyOfPackages "git" "git-core"}}# We trust our base image and the repos that are pulled in workflows. Otherwise
# each workflow that uses our base images would have to add the step below.
RUN git config --system --add safe.directory '*';
{{end}}ENTRYPOINT ["/bin/bash"]
